namespace: hasnimehdi91
name: cis_hardening
version: 1.0.10
readme: README.md
authors:
- Hasni Mehdi hasnimehdi@outlook.com
description: This collection provides roles for the center of internet security benchmarks.
license_file: 'LICENSE'
tags:
- cis_hardening
- cis
- linux
- linux_security
- cis_linux
- linux_benchmark
- cis_benchmark
dependencies: {}
repository: https://github.com/Black-Cockpit/cis-hardening
documentation: https://github.com/Black-Cockpit/cis-hardening/blob/master/doc
homepage: https://github.com/Black-Cockpit/cis-hardening
issues: https://github.com/Black-Cockpit/cis-hardening/issues
build_ignore:
- .git
- .gitignore
- .build_ignore
- .vscode
- .env
- .venv
- .vagrant
- .pytest_cache
- .tox
- .cache
- .coverage
- .ropeproject
- .ackrc
- .python-version
- .DS_Store
- .idea
- .project
- .pydevproject
- '*.tar.gz'
- '*.pyc'
- '*.pyo'
- '*.retry'
- '*.log'
- '*.out'
- '*.swp'
- '*.swo'
- '*.iml'
- '*.sublime-project'
- '*.sublime-workspace'
- __pycache__
- build.venv
- test
- tests
- molecule
- venv
- env
- ENV
- env.bak
- venv.bak
- Vagrantfile
- requirements.txt
- credentials.yml
- results.xml
- coverage.xml
- htmlcov
- changelogs/.plugin-cache.yaml
- .ansible-test-timeout.json
