# Check if module is disabled
- name: "Pre Remediation | 3.1.2 Ensure wireless interfaces are disabled"
  shell:
    cmd: 'grep -r -E "^(#)?install {{ item }} /bin/true" /etc/modprobe.d/ > /dev/null && echo disabled || echo not_disabled'
  changed_when: false
  register: wireless_module_check_disabled_result

# Check if module is blacklisted
- name: "Pre Remediation | 3.1.2 Ensure wireless interfaces are disabled"
  shell:
    cmd: 'grep -r -E "^(#)?blacklist {{ item }}" /etc/modprobe.d/ > /dev/null && echo blacklisted || echo not_blacklisted'
  changed_when: false
  register: wireless_module_blacklisted_check_result


# 3.1.2 Ensure wireless interfaces are disabled | Remediation
- name: "3.1.2 Ensure wireless interfaces are disabled | Remediation"
  lineinfile:
    path: "/etc/modprobe.d/{{ item }}.conf"
    regexp: "^(#)?install {{ item }}(\\s|$)"
    line: "install {{ item }} /bin/true"
    create: true
    mode: "0600"
  when: wireless_module_check_disabled_result != 'disabled'

# 3.1.2 Ensure wireless interfaces are disabled | Remediation
- name: "3.1.2 Ensure wireless interfaces are disabled | Remediation"
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    regexp: "^(#)?blacklist {{ item }}(\\s|$)"
    line: "blacklist {{ item }}"
    create: true
    mode: "0600"
  when: wireless_module_blacklisted_check_result != 'blacklisted'

# Disable wireless module filesystems
- name: Disabling {{ item }} filesystems
  modprobe:
    name: {{ item }}
    state: absent